"use strict";
const assert = require("node:assert/strict");
const sub = require("../subtitle-core.js");
const capture = require("../capture-core.js");
const id = "7679517661952265514";
const url = "https://v3.douyinvod.com/subtitle/captions.json";
const nested = { aweme_id: id, video: { cla_info: { original_language_info: { language: "zh" }, caption_infos: [{ url, lang: "zh", Format: "creator_caption" }] } } };
assert.equal(capture.extractPlayableItems(nested).length, 0);
const item = capture.extractSubtitleItems(nested)[0];
assert.equal(item.awemeId, id);
assert.equal(item.url, "");
assert.equal(item.subtitleTracks[0].url, url);
assert.equal(item.subtitleTracks[0].original, true);
const sticker = { awemeId: id, interaction_stickers: [{ auto_video_caption_info: { auto_captions: [{ language: "zh", url: { url_list: [url] } }] } }] };
assert.equal(capture.extractSubtitleItems(sticker)[0].subtitleTracks[0].url, url);
const camel = { awemeId: id, video: { claInfo: { captionInfos: JSON.stringify([{ Url: { UrlList: [url] }, LanguageCodeName: "zh" }]) } } };
assert.equal(capture.extractSubtitleItems(camel)[0].subtitleTracks[0].url, url);
const inline = { aweme_id: id, video: { caption_info: { utterances: [{ start_time: 1200, end_time: 2500, text: "这是现成字幕，不是描述" }] } } };
assert.deepEqual(capture.extractSubtitleItems(inline)[0].nativeSegments, [{ start: 1.2, end: 2.5, text: "这是现成字幕，不是描述" }]);
assert.equal(capture.extractSubtitleItems({ aweme_id: id, desc: "不应拿视频标题冒充字幕", video: { cover: { url_list: [url] } } }).length, 0);
assert.equal(capture.extractSubtitleItems(encodeURIComponent(JSON.stringify(nested)))[0].awemeId, id);
const previous = { awemeId: id, title: "视频标题", url: "https://v3.douyinvod.com/full.mp4", subtitleTracks: [{ url, language: "zh" }] };
const merged = sub.mergeItems(previous, { awemeId: id, title: "", url: "", nativeSegments: [{ start: 0, end: 1, text: "后来返回的字幕" }] });
assert.equal(merged.url, previous.url);
assert.equal(merged.title, previous.title);
assert.equal(merged.subtitleTracks.length, 1);
assert.equal(merged.nativeSegments.length, 1);
assert.equal(sub.mergeItems(previous, { awemeId: "7679517661952265515", title: "另一条", url: "" }).subtitleTracks, undefined);
assert.doesNotThrow(() => sub.extractTracks({ interaction_stickers: {} }));
assert.equal(sub.extractTracks({ video: { caption_infos: [{ url: "https://douyinvod.com.evil.example/sub.vtt" }] } }).length, 0);
console.log("native-extraction.test.js: passed (isolated schema fixtures; nested/sticker/camel/inline sources, no-MP4 extraction, merging, video identity, URL guards)");
